// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfF-gkgRRo8RVtp3FNTWOIqDdwPCnl9Ww',
    appId: '1:764042909411:web:ce20ff9d0ff59305d057d6',
    messagingSenderId: '764042909411',
    projectId: 'notification-69e96',
    authDomain: 'notification-69e96.firebaseapp.com',
    storageBucket: 'notification-69e96.firebasestorage.app',
    measurementId: 'G-JX7KEWG1VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXq1lMXDpPIBh_-_Y5DL0Qm7SCVSvBexI',
    appId: '1:764042909411:android:830028586783a3c8d057d6',
    messagingSenderId: '764042909411',
    projectId: 'notification-69e96',
    storageBucket: 'notification-69e96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFvVV_gNLUCuEDq4CwJ_ZGAcKwVk1Ryps',
    appId: '1:764042909411:ios:d4c1d65cdd62855dd057d6',
    messagingSenderId: '764042909411',
    projectId: 'notification-69e96',
    storageBucket: 'notification-69e96.firebasestorage.app',
    iosBundleId: 'com.nxl.nxlFlutterAuthTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFvVV_gNLUCuEDq4CwJ_ZGAcKwVk1Ryps',
    appId: '1:764042909411:ios:6a2c1ae69bcd6e4ad057d6',
    messagingSenderId: '764042909411',
    projectId: 'notification-69e96',
    storageBucket: 'notification-69e96.firebasestorage.app',
    iosBundleId: 'com.example.nxlFlutterAuthTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfF-gkgRRo8RVtp3FNTWOIqDdwPCnl9Ww',
    appId: '1:764042909411:web:341331b77c0735a4d057d6',
    messagingSenderId: '764042909411',
    projectId: 'notification-69e96',
    authDomain: 'notification-69e96.firebaseapp.com',
    storageBucket: 'notification-69e96.firebasestorage.app',
    measurementId: 'G-VG050XFD16',
  );
}
